### ISSUE TITLE
Extension icon not showing

### ISSUE THREAD

**Issue by G00fY2** [neaumusic/selection-highlighter#13]
![unbenannt](https://user-images.githubusercontent.com/1990806/44310395-93554280-a3d5-11e8-8d19-27c06f3f82b5.PNG)

Any reason you didnt add the icon to the manifest? =)

**Comment by neaucode** [comment]
just lazy I guess 😅 but  these are good,  thank you for filing

**Comment by G00fY2** [comment]
I know this is just a small project, but its actually very helpful in my everyday life as a developer.:smiley: I already recommended it to my colleagues and they also find it very handy while browsing github or stackoverflow.

Just think with a better presentation and readme page (e.g. install guide for chrome store and install via developer settings) many other pople would find and use your extension.

Maybe if I find some time I will post some PRs.:blush:

**Comment by neaucode** [comment]
fixed -- https://github.com/neaumusic/selection-highlighter/commit/154ff6d028cbe98fa83307baf09eadc01c5552ea
