### ISSUE TITLE
Match whole word option

### ISSUE THREAD

**Issue by mkielek** [neaumusic/selection-highlighter#14]
It would be a nice to have option to highlight a matched whole word.

**Comment by neaumusic** [comment]
this is a good idea
first step may be to expose the `match` regex, though the leading and trailing spaces need to be matched as well.. probably will put a comment in options.js
next step would be to add a UI slider for windowLocation and regex toggle buttons similar to sublime (case insensitive + whole word)

**Comment by neaucode** [comment]
finally got around to doing this
make sure to copy existing configs, then just "reset to default" in chrome extension options

https://github.com/neaumusic/selection-highlighter/commit/b42591c4a6284f7516cf7d24de4c2f3318626dd5
