### ISSUE TITLE
React development error on removeChild execution

### ISSUE THREAD

**Issue by clever-dan-torczynski** [neaumusic/selection-highlighter#19]
Developing a react app on chrome and this extension is causing a rendering error. I've isolated it to this extension by turning off all other extensions installed except for this, and showing the error occurs with it enabled, and doesn't occur without it enabled. 
This only started occurring recently, eg past week or so, I'm using Chrome Version 77.0.3865.75 (Official Build) (64-bit)
Screen shot of error:
![Screen Shot 2019-10-17 at 1 34 09 PM](https://user-images.githubusercontent.com/31490527/67045310-e06c9b80-f0e2-11e9-8977-ab5d5af41a00.png)

While debugging, I noticed this occurs particularly during a state change in react and a re-render happens. I've added debug statements, and can tell that all the render functions complete successfully, and the error is occurring as part of the underlying DOM rebuilding.
My guess is there is a race condition occurring between a node being removed while simultaneously expecting to be present in the DOM. 
Happy to share more info, or try modifying my extension config settings to debug further.
Worth noting this error occurs just logged in as a regular user attempting to navigate the site (eg so not only for the developer use case) and I'll have to disable this extension until its fixed.

**Comment by neaucode** [comment]
Interesting, thanks for filing, I'll look over the code again!

**Comment by neaucode** [comment]
It seems strange that `removeChild` is being used in App.js, and that the child of App.js would have split text (a replaced child)
Is App.js using a `ref` or an old DOM node? Also, when this error occurs, does chrome dev tools show that DOM node being replaced or updated by the extension (does it flash)?

**Comment by clever-dan-torczynski** [comment]
> Is App.js using a ref or an old DOM node?

Not sure offhand, is there a way I could check this?

> when this error occurs, does chrome dev tools show that DOM node being replaced or updated by the extension (does it flash)?

Not seeing anything flash, although I just realized my error case flow is probably triggering the extension. To cause the error, with my mouse I'm highlighting existing text in the app display in a text input box, and pasting in previously copied alternate text. The pasting changes react state which triggers the DOM restructuring and the removeChild error.
If instead of highlighting, then pasting in over the highlight portion, I just backspace the existing text and paste in an empty box, there is no error.

**Comment by neaucode** [comment]
there's been a bug of unnecessary normalization of all text nodes on the page, I'm thinking it may fix this and I want to close this unless more info comes up
