### ISSUE TITLE
not work with Chinese properly

### ISSUE THREAD

**Issue by cc978** [neaumusic/selection-highlighter#25]
good works
but ...
for example, search "小智 赵薇" in google

for "万家文化", it works
![image](https://user-images.githubusercontent.com/63266600/82980567-5b544800-a01c-11ea-97c4-2f2a15f6f4af.png)

not works for "万家"
![image](https://user-images.githubusercontent.com/63266600/82980592-69a26400-a01c-11ea-9436-1d2348d9d82a.png)

not works for "小智"
![image](https://user-images.githubusercontent.com/63266600/82980635-83dc4200-a01c-11ea-959c-34d4f748b7e7.png)

can not figure out the logic ...

and BTW it not works for all numbers?? like "2020"

**Comment by cc978** [comment]
figure out some logic:
works with more than three English or number, Chinese

**Comment by neaucode** [comment]
Hello friend, glad it's working! Yep it's an issue of `length` -- if you change the Options then it should work:

```
  isSelectionValid: function ({ selectionString, selection }) {
    return (selectionString.length >= 3 && !/None|Caret/.exec(selection.type));
  },
```

change to `selectionString.length >= 1` maybe !!

you might be able to determine that the characters are chinese in that function (`length > 3` is pretty safe if it's english)

---

```
'万家'.charCodeAt(0)
19975
'万家文化'.charCodeAt(0)
19975
'万家'.charCodeAt(1)
23478
'万家文化'.charCodeAt(1)
23478
```

**Comment by neaucode** [comment]
I will put this at the top of the Options, and I'll simplify the cryptic `!/None|Caret/.exec` part
