### ISSUE TITLE
pressedKeys sometimes gets stuck

### ISSUE THREAD

**Issue by ryancu7** [neaumusic/selection-highlighter#28]
### Steps to reproduce
1. Uncomment the line `return pressedKeys.includes('Alt'); ` in the extension's settings JavaScript.
2. Reload a page to test the new settings. 
3. Double click a common word on the test page. 
➜ No other instances are highlighted. 👍
4. Hold down Alt and double click a common word.
➜ All the other instances are highlighted. 👍
5. Press Alt + Tab to switch to another application or window.
6. Return to the test webpage.
7. Double click a common word on your test page. 
➜ All the other instances are highlighted. 👎

**Comment by neaucode** [comment]
Great repro steps, thank you, and it makes sense that pressedKeys doesnt hear the keyup event if chrome doesn’t have focus, so I’ll try to think of a better solution
