### ISSUE TITLE
distorted highlight in "code" blocks

### ISSUE THREAD

**Issue by Rimpel** [neaumusic/selection-highlighter#35]
on some pages (for example help pages in https://docs.microsoft.com), if word that can be found in «code» blocks highlited, it is highlighted with huge offset:
![image](https://user-images.githubusercontent.com/22381438/111867774-3f44dd00-8987-11eb-94ec-4f37cb34d19d.png)

**Comment by neaucode** [comment]
looks like this is due to CSS on the page for `mark` in a code block

"display: inline-block" and "width: calc(100% + 2rem)"

**Comment by neaucode** [comment]
you might be able to fix this in options by enabling the `// display: inline` style

**Comment by Rimpel** [comment]
Yes, it helped, thanks
