### ISSUE TITLE
High CPU usage on trello.com

### ISSUE THREAD

**Issue by openaphid** [neaumusic/selection-highlighter#40]
As reported in [Trello community](https://community.atlassian.com/t5/Trello-questions/High-CPU-when-Trello-is-at-foreground-on-Chrome-89-0-4389-114/qaq-p/1688174#U1688339), `selection-highlighter` causes high CPU usage on trello.com.

Adding trello.com to blacklisted hosts doesn't fix the issue.

**Comment by openaphid** [comment]
It seems it's not actually caused by `selection-highlighter`. I need to look into it.

**Comment by neaucode** [comment]
@openaphid no worries! you should use the DevTools 'Profiler' panel and just hit the record button, cause the cpu usage, stop recording, and switch to the 'Chart' view which is a flamegraph and you can see which segments are expensive or recursing
