### ISSUE TITLE
The extension no longer works (Chrome)

### ISSUE THREAD

**Issue by krosa100** [neaumusic/selection-highlighter#62]
Default settings. When selecting text, nothing on the page is hilighted.

**Comment by neaucode** [comment]
It definitely still works, are you on mac/windows and which site / area are you clicking in? @krosa100

**Comment by krosa100** [comment]
You are correct. It works. I may have accidentally had a "Gate Key" set. 
Awesome extension, by the way! I've tested 4 with a similar goal, and it's by far the best. Thank you.

**Comment by krosa100** [comment]
Actually, the extension appears not to work on the chrome extension page.
https://chrome.google.com/webstore/detail/selection-highlighter/nepmkgohgoagfgcoegjaggacodcpdibj

This is hardly a concern if it's just this page, of course.

**Comment by neaucode** [comment]
haha, ok cool, yea it cant run on the webstore due to security concerns, I've seen some pages (iframes?) where it also doesn't work, but they're pretty far and few between 🙂
